services:
  blockchain:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - "8545:8545"
    command: anvil --host 0.0.0.0

  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
    tty: true
    stdin_open: true
    depends_on:
      - blockchain